/**
 * replicad-opencascadejs custom build, expressed for `@libcascade/toolchain`.
 *
 * The single source of truth for both variants: `libcascade build` renders the
 * container-side yml from this file and `libcascade assemble` generates the
 * packaging surface in `dist/`. The custom C++ under `build-config/wrappers/`
 * is referenced in place by `customBindings` below.
 */
import { defineBuild } from "@libcascade/toolchain";

export default defineBuild({
  name: "replicad",
  bindings: [
    "Message_ProgressRange",
    "TColgp_Array1OfDir",
    "TColgp_Array1OfPnt",
    "TColgp_Array1OfPnt2d",
    "TColgp_Array2OfPnt",
    "TColStd_Array1OfBoolean",
    "TColgp_Array1OfVec",
    "TColStd_Array1OfInteger",
    "TColStd_Array1OfReal",
    "Poly_Array1OfTriangle",
    "Standard_Transient",
    "Standard_Failure",
    "Precision",
    "Interface_Static",
    "Interface_InterfaceModel",
    "Interface_TypedValue",
    "MoniTool_TypedValue",
    "StepData_StepModel",
    "gp_XYZ",
    "gp_XY",
    "gp_Vec",
    "gp_Pnt",
    "gp_Dir",
    "gp_Ax1",
    "gp_Ax2",
    "gp_Ax3",
    "gp_Circ",
    "gp_Pln",
    "gp_Elips",
    "gp_Cylinder",
    "gp_Sphere",
    "gp_Trsf",
    "gp_GTrsf",
    "Geom2d_Line",
    "Geom2d_Curve",
    "Geom2d_OffsetCurve",
    "Geom2d_BoundedCurve",
    "Geom2d_TrimmedCurve",
    "Geom2d_BezierCurve",
    "Geom2d_BSplineCurve",
    "Geom2d_Geometry",
    "Geom2d_Ellipse",
    "Geom2d_Circle",
    "Geom2d_Conic",
    "Geom_SphericalSurface",
    "Geom_ElementarySurface",
    "gp_Vec2d",
    "gp_Pnt2d",
    "gp_Dir2d",
    "gp_Ax2d",
    "gp_Ax22d",
    "gp_Circ2d",
    "gp_Elips2d",
    "GC_MakeSegment2d",
    "GC_MakeArcOfCircle2d",
    "GC_MakeArcOfEllipse2d",
    "GC_MakeCircle2d",
    "GC_MakeEllipse2d",
    "GeomLib",
    "gp_Trsf2d",
    "gp_GTrsf2d",
    "Bnd_Box2d",
    "BndLib_Add2dCurve",
    "Geom2dAPI_InterCurveCurve",
    "Geom2dAPI_ProjectPointOnCurve",
    "Geom2dAPI_PointsToBSpline",
    "Geom2dAPI_ExtremaCurveCurve",
    "Bnd_Box",
    "Bnd_OBB",
    "BRepBndLib",
    "GeomAbs_CurveType",
    "GeomAbs_SurfaceType",
    "GeomAbs_Shape",
    "GeomTools",
    "Geom_Geometry",
    "Geom_Curve",
    "Geom_Surface",
    "Geom_ElementarySurface",
    "Geom_ConicalSurface",
    "Geom_CylindricalSurface",
    "Geom_BoundedSurface",
    "Geom_BSplineSurface",
    "Geom_BoundedCurve",
    "Geom_TrimmedCurve",
    "Geom_BezierCurve",
    "Geom_BSplineCurve",
    "GeomAPI_Interpolate",
    "GeomAPI_PointsToBSpline",
    "GeomAPI_PointsToBSplineSurface",
    "GeomAPI_ProjectPointOnSurf",
    "TopoDS",
    "TopoDS_Edge",
    "TopoDS_Face",
    "TopoDS_Wire",
    "TopoDS_Shell",
    "TopoDS_Vertex",
    "TopoDS_Solid",
    "TopoDS_Compound",
    "TopoDS_CompSolid",
    "TopoDS_Shape",
    "TopoDS_Builder",
    "TopAbs_ShapeEnum",
    "TopTools_ListOfShape",
    "TopAbs_Orientation",
    "TopLoc_Location",
    "TopExp_Explorer",
    "TopTools_ListOfShape",
    "NCollection_BaseList",
    "Poly_Connect",
    "BRepLib_ToolTriangulatedShape",
    "Poly_Triangle",
    "Poly_Triangulation",
    "Poly_PolygonOnTriangulation",
    "BinTools",
    "BRep_Tool",
    "BRepLib",
    "BRepTools",
    "BRepGProp",
    "BRepGProp_Face",
    "GProp_GProps",
    "GC_MakeArcOfCircle",
    "GC_MakeArcOfEllipse",
    "GC_Root",
    "GCPnts_TangentialDeflection",
    "BRepMesh_IncrementalMesh",
    "BRepMesh_DiscretRoot",
    "OSD_ThreadPool",
    "BRepAdaptor_Surface",
    "BRepAdaptor_Curve",
    "Adaptor3d_Curve",
    "Adaptor3d_Surface",
    "BRepAdaptor_CompCurve",
    "GeomAdaptor_TransformedSurface",
    "GeomAdaptor_TransformedCurve",
    "Geom2dAdaptor_Curve",
    "Adaptor2d_Curve2d",
    "BRepAdaptor_Curve2d",
    "Geom2dConvert_BSplineCurveToBezierCurve",
    "Geom2dConvert_ApproxCurve",
    "Geom2dConvert",
    "Convert_ParameterisationType",
    "GeomConvert",
    "StlAPI_Writer",
    "STEPControl_Writer",
    "STEPControl_StepModelType",
    "IFSelect_ReturnStatus",
    "Law_Function",
    "Law_Linear",
    "Law_Composite",
    "Law_Interpol",
    "Law_BSpFunc",
    "Law_S",
    "BRepAlgoAPI_Algo",
    "BRepAlgoAPI_BuilderAlgo",
    "BRepAlgoAPI_BooleanOperation",
    "BRepAlgoAPI_Cut",
    "BRepAlgoAPI_Fuse",
    "BOPAlgo_GlueEnum",
    "BOPAlgo_Options",
    "BRepAlgoAPI_Section",
    "BRepAlgoAPI_Common",
    "BRepExtrema_DistShapeShape",
    "BRepBuilderAPI_ModifyShape",
    "BRepBuilderAPI_MakeShape",
    "BRepBuilderAPI_Command",
    "BRepBuilderAPI_Transform",
    "BRepBuilderAPI_MakeEdge",
    "BRepBuilderAPI_MakeWire",
    "BRepBuilderAPI_MakeFace",
    "BRepBuilderAPI_MakeVertex",
    "BRepBuilderAPI_MakeSolid",
    "BRepBuilderAPI_TransitionMode",
    "BRepBuilderAPI_Sewing",
    "BRepBuilderAPI_WireError",
    "BRepBuilderAPI_MakeShell",
    "BRepPrimAPI_MakeOneAxis",
    "BRepPrimAPI_MakeCylinder",
    "BRepPrimAPI_MakeBox",
    "BRepCheck_Analyzer",
    "BRepPrimAPI_MakeSweep",
    "BRepPrimAPI_MakePrism",
    "BRepPrimAPI_MakeRevol",
    "BRepPrimAPI_MakeSphere",
    "BRepPrimAPI_MakeTorus",
    "BRepPrimAPI_MakeRevolution",
    "BRepOffsetAPI_DraftAngle",
    "BRepOffsetAPI_ThruSections",
    "BRepOffsetAPI_MakeThickSolid",
    "BRepOffsetAPI_MakeOffset",
    "BRepOffsetAPI_MakeOffsetShape",
    "BRepOffsetAPI_MakePipe",
    "BRepOffsetAPI_MakePipeShell",
    "BRepOffsetAPI_MakeFilling",
    "BRepOffset_Mode",
    "BRepFilletAPI_LocalOperation",
    "BRepFilletAPI_MakeFillet",
    "BRepFilletAPI_MakeChamfer",
    "BRepFeat_MakeDPrism",
    "BRepFeat_Form",
    "ChFi3d_FilletShape",
    "ChFiDS_ChamfMode",
    "GeomAbs_JoinType",
    "BRepFill_TypeOfContact",
    "Extrema_ExtAlgo",
    "ShapeFix_Root",
    "ShapeFix_Solid",
    "ShapeFix_Face",
    "ShapeFix_Wire",
    "STEPControl_Reader",
    "XSControl_Reader",
    "StlAPI_Reader",
    "ShapeUpgrade_UnifySameDomain",
    "ShapeFix_EdgeConnect",
    "StlAPI",
    "HLRBRep_Algo",
    "HLRBRep_InternalAlgo",
    "HLRAlgo_Projector",
    "HLRBRep_HLRToShape",
    "CDM_Document",
    "TDF_Attribute",
    "TDataStd_GenericEmpty",
    "TDocStd_Document",
    "TDataStd_GenericExtString",
    "XCAFDoc_LengthUnit",
    "TCollection_ExtendedString",
    "TCollection_HAsciiString",
    "XCAFDoc_DocumentTool",
    "XCAFDoc_ShapeTool",
    "XCAFDoc_ColorTool",
    "XCAFDoc_MaterialTool",
    "TDF_Label",
    "TDataStd_Name",
    "Quantity_ColorRGBA",
    "Quantity_Color",
    "XCAFDoc_ColorType",
    "XSControl_WorkSession",
    "STEPCAFControl_Writer",
    "STEPControl_StepModelType",
    "IFSelect_ReturnStatus",
    "IFSelect_WorkSession",
    "BRepToolsWrapper",
    "GeomToolsWrapper",
    "ReplicadShapeHasher",
    "ReplicadShapeCaster",
    "ReplicadMeshData",
    "ReplicadMeshExtractor",
    "ReplicadEdgeMeshData",
    "ReplicadEdgeMeshExtractor",
    "ReplicadRuntimeInfo",
    "ReplicadStepModelTools",
    "ReplicadPrototypeMeshData",
    "ReplicadPrototypeEdgeMeshData",
    "ReplicadPrototypeIdData",
    "ReplicadPrototypeMeshExtractor",
    "ReplicadShapeIdentityInfo",
    "ReplicadShapeIdentity",
    "ReplicadBooleanBatchResult",
    "ReplicadBooleanBatch",
  ],
  customBindings: [
    {
      file: "build-config/wrappers/shape-hasher.cpp",
      symbols: ["ReplicadShapeHasher"],
    },
    {
      file: "build-config/wrappers/shape-caster.cpp",
      symbols: ["ReplicadShapeCaster"],
    },
    {
      file: "build-config/wrappers/mesh-extractor.cpp",
      symbols: ["ReplicadMeshData", "ReplicadMeshExtractor"],
    },
    {
      file: "build-config/wrappers/edge-mesh-extractor.cpp",
      symbols: ["ReplicadEdgeMeshData", "ReplicadEdgeMeshExtractor"],
    },
    {
      file: "build-config/wrappers/brep-io.cpp",
      symbols: ["BRepToolsWrapper"],
    },
    {
      file: "build-config/wrappers/geom2d-io.cpp",
      symbols: ["GeomToolsWrapper"],
    },
    {
      file: "build-config/wrappers/step-model-tools.cpp",
      symbols: ["ReplicadStepModelTools"],
    },
    {
      file: "build-config/wrappers/runtime-info.cpp",
      symbols: ["ReplicadRuntimeInfo"],
    },
    {
      file: "build-config/wrappers/prototype-mesh-extractor.cpp",
      symbols: [
        "ReplicadPrototypeMeshData",
        "ReplicadPrototypeEdgeMeshData",
        "ReplicadPrototypeIdData",
        "ReplicadPrototypeMeshExtractor",
      ],
    },
    {
      file: "build-config/wrappers/shape-identity.cpp",
      symbols: ["ReplicadShapeIdentityInfo", "ReplicadShapeIdentity"],
    },
    {
      file: "build-config/wrappers/boolean-batch.cpp",
      symbols: ["ReplicadBooleanBatchResult", "ReplicadBooleanBatch"],
    },
  ],
  settings: {
    EXPORT_ES6: true,
    MODULARIZE: true,
    ALLOW_MEMORY_GROWTH: true,
    INITIAL_MEMORY: "100MB",
    MAXIMUM_MEMORY: "4GB",
    EXPORTED_RUNTIME_METHODS: [
      "FS",
      "wasmMemory",
      "getExceptionMessage",
      "incrementExceptionRefcount",
      "decrementExceptionRefcount",
    ],
    ENVIRONMENT: ["web", "worker", "node"],
    STACK_SIZE: 8_388_608,
    WASM_BIGINT: true,
  },
  compilerFlags: {
    exceptions: "wasm",
    noEntry: true,
    simd: true,
    optimize: "O3",
  },
  variants: [
    // Pre-evaluate global constructors to reduce single-threaded startup work.
    { name: "single", settings: { EVAL_CTORS: 2 } },
    {
      name: "multi",
      // `requires: ['threads']` is inferred from the flags below, so it is not
      // declared. `-pthread` replaces the deprecated `USE_PTHREADS` setting,
      // which emcc keeps only as a legacy alias of exactly this flag.
      compilerFlags: { threads: true },
      settings: {
        SHARED_MEMORY: true,
      },
      // Emscripten emits this expression verbatim. Node 20 has no navigator,
      // so use four pre-spawned workers there while capable hosts stay adaptive.
      rawFlags: [
        "-sPTHREAD_POOL_SIZE=globalThis.navigator?.hardwareConcurrency??4",
      ],
    },
  ],
});
